### ISSUE TITLE
'tests' KeyError on install

### ISSUE THREAD

**Issue by xulb** [xulb/aaserver#1]
Animal:
"Now I'm getting this error:

Traceback (most recent call last):
File "/usr/local/lib/python3.4/site-packages/setuptools-2.0.2-py3.4.egg/pkg_resources.py", line 226, in get_provider
KeyError: 'tests'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "setup.py", line 10, in <module>
dum = resource_string('tests','testArgs.py')
File "/usr/local/lib/python3.4/site-packages/setuptools-2.0.2-py3.4.egg/pkg_resources.py", line 890, in resource_string
File "/usr/local/lib/python3.4/site-packages/setuptools-2.0.2-py3.4.egg/pkg_resources.py", line 228, in get_provider
ImportError: No module named 'tests'"

**Comment by xulb** [comment]
8da3a80 fixed #2 not #1. oops
